---
project: fntva

environments:
  dev:
    cloud:
      provider: aws
      region: <region>
      account_id: <account>

    security:

    cluster:
      dynamic_hosts: 1
      statics_hosts_max: 1
      micro_services:
        - fastapi
        - django
...
