---
zone:

environments:
  dev:
    cloud:
      provider:
      region:
      account_id:

    networking:
      vpc_cidr:
      availability_zones:
      subnet_bits_mask:

    security:
      ssl_certificate_arn:

    dns:
      domain_name:

    cluster:
      dynamic_hosts:
      statics_hosts_max:
      micro_services:
        -
...
