---
environments:
  dev:
    cloud:
      provider: aws
      region: us-east-1
      account_id: 199920436475

    security:

    cluster:
      dynamic_hosts: 1
      statics_hosts_max: 1
      micro_services:
        - fastapi
        - django
...
